const certificates = [
  {
    id: 1,
    imageName: "OOPs.svg",
    certificateName: "Object Oriented Programming",
    courseName: "Fundamentals of Object Oriented Programming",
    issuingOrganization: "NPTEL",
    issueDate: "2025-04-15",
    credentialURL: "https://internalapp.nptel.ac.in/NOC/NOC25/SEM1/Ecertificates/106/noc25-cs34/Course/NPTEL25CS34S55760034104306720.pdf",
  },
  {
    id: 2,
    imageName: "AWS.svg", 
    certificateName: "AWS Academy Graduate",
    courseName: "AWS Academy Cloud Foundations",
    issuingOrganization: "AWS Academy",
    issueDate: "2024-09-16",
    credentialURL: "https://www.credly.com/go/JFkJPCcG",
  },
  {
    id: 3,
    imageName: "FullStack-1.png",
    certificateName: "Full Stack",
    courseName: "Full Stack Web Development",
    issuingOrganization: "Coursera",
    issueDate: "2024-08-15",
    credentialURL: "https://www.credly.com/go/7tALCT18",
  },
  {
    id: 4,
    imageName: "React.svg",
    certificateName: "Advance React",
    courseName: "Advance React.js Programming",
    issuingOrganization: "Coursera",
    issueDate: "2024-07-12",
    credentialURL: "https://www.credly.com/your-badge-url",
  },
  {
    id: 5,
    imageName: "Prompt.svg",
    certificateName: "Prompt Engineering",
    courseName: "Prompt Engineering",
    issuingOrganization: "Coursera",
    issueDate: "2024-01-10",
    credentialURL: "https://www.coursera.org/account/accomplishments/specialization/L3DC2YS8CGML",
  },
  {
    id: 6,
    imageName: "Back-End.svg",
    certificateName: "Developing Back-End",
    courseName: "Developing Back-End Apps with Node.js and Expart",
    issuingOrganization: "Coursera",
    issueDate: "2024-01-10",
    credentialURL: "https://www.coursera.org/account/accomplishments/verify/CLBZM9NRDJWD",
  },
  {
    id: 7,
    imageName: "Web-Development.svg",
    certificateName: "Web Development",
    courseName: "Introduction to Web Development with HTML, CSS, JavaScript",
    issuingOrganization: "Coursera",
    issueDate: "2024-01-10",
    credentialURL: "https://www.coursera.org/account/accomplishments/verify/X6XZSKJ6O774",
  },
  {
    id: 8,
    imageName: "Data-Analysis.svg",
    certificateName: "Data-Analysis",
    courseName: "Data-Analysis-with-Python",
    issuingOrganization: "Coursera",
    issueDate: "2024-01-10",
    credentialURL: "https://www.coursera.org/account/accomplishments/verify/GT59NYY5QY7Q",
  },
  {
    id: 9,
    imageName: "Git-and-GitHub.svg",
    certificateName: "Git-and-GitHub Cource",
    courseName: "Getting-Started-with-Git-and-GitHub",
    issuingOrganization: "Coursera",
    issueDate: "2024-01-10",
    credentialURL: "https://www.coursera.org/account/accomplishments/verify/Q4RL3DCPBFKF",
  },
  {
    id: 10,
    imageName: "JavaScript.svg",
    certificateName: "JavaScript Programming",
    courseName: "Programming-with-JavaScript",
    issuingOrganization: "Coursera",
    issueDate: "2024-01-10",
    credentialURL: "https://www.coursera.org/account/accomplishments/verify/ZC5URBEX4YDY",
  },
  {
    id: 11,
    imageName: "Full-Stack-Software.svg",
    certificateName: "IBM Full Stack Software Developer",
    courseName: "IBM Full Stack Software Developer",
    issuingOrganization: "Coursera",
    issueDate: "2024-01-10",
    credentialURL: "https://www.coursera.org/account/accomplishments/professional-cert/6ZJRILWWHSQW",
  },
];

export default function handler(req, res) {
  res.status(200).json(certificates);
}
